name: "Generate code pairs"
on:
  schedule:
  - cron: "0 14 * * Tue expr `date +\%s` / 604800 \% 2"

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run python script
        run: python runner.py
