---
hobbits:
  - brudolph
  - tsheffels
  - jemord
#  - nhooper
  - ncarnahan
#  - sreddy
  - frener
  - npellegrino

enchantresses:
  - jschweers
#  - czue
  - droberts
#  - dmiller - offline 8/6 - 10/5
#  - skelly
  - esoergel
  - gcapalbo
  - biyeun
