---
# INSTRUCTIONS
# 'username' is your dimagi email username
#
# For now, only add entries to 'hobbits'
hobbits:
  - gherceg
  - dmiller
  - jtang
  - aphulera
  - emapson
  - rcostello
  - sherbers
  - esoergel
  - csmit
  - chris.smit

enchantresses: []
# -- do not add here --
