---
hobbits:
  - brudolph
  - tsheffels
  - jemord
  - nhooper
  - ncarnahan
  - sreddy
  - frener
  - twymer
  
enchantresses:
  #- npellegrino offline 5/25 - 6/1
  - jschweers
  - czue
  - droberts
  - dmiller
  - skelly
  - esoergel
  - gcapalbo
  # - biyeun offline until may 25
