---
hobbits:
  - nhooper
  - sreddy
  - frener
  - npellegrino
  - droberts
  - dmiller
  - skelly
  - esoergel
  - biyeun
  - cellowitz
  - mkangia
  - jschweers
  - jemord
  - gbova
  - rnegi


enchantresses: []
