---
# INSTRUCTIONS
# 'username' is your dimagi email username
#
# For now, only add entries to 'hobbits'
hobbits:
  - gherceg
  - dmiller
  - jtang
  - aphulera
  - emapson
  - rcostello

enchantresses: []
# -- do not add here --
