---
hobbits:
  - brudolph
  - tsheffels
  - jemord
  - nhooper
  - ncarnahan
  - sreddy
  - frener
  - jschweers

enchantresses:
  - npellegrino
  - czue
  - droberts
  - dmiller
  - skelly
  - esoergel
  - gcapalbo
  # - biyeun offline until may 25
