---
hobbits:
  - brudolph
  - nhooper
  - ncarnahan
  - sreddy
  - frener
  - npellegrino
  - czue
  - droberts
  - dmiller
  - skelly
  - esoergel
  - gcapalbo
  - biyeun
  - cellowitz
  - mkangia
  - jschweers
  - jemord
  - jwilson


enchantresses: []
