---
hobbits:
  - brudolph
  - tsheffels
  - jemord
  - nhooper
  - ncarnahan
  - sreddy
  - frener
  - npellegrino

enchantresses:
  - jschweers
  - czue
  - droberts
  - dmiller
  - skelly
  - esoergel
  - gcapalbo
  - biyeun
