---
hobbits:
  - brudolph
  - tsheffels
#  - jemord - offline 10/7 - 10/31
  - nhooper
  - ncarnahan
  - sreddy
  - frener
  - npellegrino
  - jschweers
  - czue
  - droberts
#  - dmiller - offline 8/6 - 10/5
  - skelly
  - esoergel
  - gcapalbo
  - biyeun
  - cellowitz

enchantresses: []
