---
hobbits:
  - nhooper
  - sreddy
  - frener
  - npellegrino
  - droberts
  - dmiller
  - skelly
  - esoergel
  - gcapalbo
  - biyeun
  - cellowitz
  - mkangia
  - jschweers
  - jemord


enchantresses: []
