name: "Generate code pairs"
on:
  schedule:
  - cron: "0 13 * * 1"  # run every Monday at 13:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/download-artifact@v3
        with:
          name: last-run
          path: last_run.txt
      - name: Check time since last run
        id: check_time
      - shell: bash
        run: |
          if [ -f last_run.txt ]; then
            fourteen_days_ago_secs=$(date --date "14 days ago" +'%s')
            last_run_secs=`cat last_run.txt`
            # if the last run was greater than or equal to 14 days ago, run
            if ["$last_run_secs" -gte "$fourteen_days_ago_secs"]; then
              should_run="yes"
            else
              should_run="no"
          else
            should_run="yes"
          echo "$should_run" >> $GITHUB_ENV
      - name: Execute python script
        if: env.should_run == "yes"
        shell: bash
        run: |
          pip install -r requirements/requirements.txt
          python runner.py
          date +'%s' > last_run.txt
      - name: Upload last_run.txt if ran
        if: env.should_run == "yes"
        uses: actions/upload-artifact@v3
        with:
          name: last-run
          path: last_run.txt