name: "Generate code pairs"
on:
  schedule:
  - cron: "0 14 1-7 * Mon"
  - cron: "0 14 15-21 * Mon"

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install requirements
        run: pip install -r requirements/requirements.txt
      - name: run python script
        run: python runner.py
