name: "Test workflow"
on:
  pull_request:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Read state.txt file
        id: read-state
        run: echo "{did_run}={$(cat .github/state.txt)}" >> $GITHUB_OUTPUT
      - name: Generate code pairs
        if: ${{ steps.read-state.outputs.did_run }} == "no"
        run: echo "Running generate code pairs"
      - name: Update state.txt to no
        if: ${{ steps.read-state.outputs.did_run }} == "no"
        run: echo "no" > .github/state.txt; git add .github/state.txt; git commit -m "update state.txt to no"; git push origin master;
      - name: Update state.txt to yes
        if: ${{ steps.read-state.outputs.did_run }} == "no"
        run: echo "yes" > .github/state.txt; git add .github/state.txt; git commit -m "update state.txt to yes"; git push origin master;
