name: code-pairing tests
on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install test requirements
        run: pip install -r requirements/test-requirements.txt
      - name: run tests
        run: nose2

